#!/bin/bash
# 
#   Copyright 2016 RIFT.IO Inc
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# Author(s): Paul Laidler
# Creation Date: 2016/01/04
#
source $RIFT_INSTALL/usr/rift/systemtest/util/mano/mano_common.sh

SCRIPT_TEST="py.test -x -v \
            ${PYTEST_DIR}/system/test_launchpad.py \
            ${PYTEST_DIR}/system/test_launchpad_longevity.py"

test_cmd=""
repeat=10
repeat_keyword="longevity"
repeat_system=1

# Parse commonline argument and set test variables
parse_args "${@}"

# Construct the test command based on the test variables
construct_test_command

# Execute from pytest root directory to pick up conftest.py
cd "${PYTEST_DIR}"

test_rc=0
for i in $(seq ${repeat_system});
do
	echo "CYCLE: $i"
	eval ${test_cmd}
	test_rc=$?
	echo "DEBUG: Got test command rc: $test_rc"
	if [[ ${test_rc} -ne 0 ]]; then
		echo "Exiting with test_rc: $test_rc"
		break
	 fi
done

# unit test XML files are converted to pretty printed format
pretty_print_junit_xml

exit ${test_rc}
