#!/bin/bash
# 
#   Copyright 2016 RIFT.IO Inc
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# Author(s): Paul Laidler
# Creation Date: 2015/07/13
#

if [ -z $AUTO_TASK_ID ]; then
    AUTO_TASK_ID=1
    export AUTO_TASK_ID
fi

source $RIFT_INSTALL/usr/rift/systemtest/util/mano/mano_common.sh

# Helper script for invoking the mission control system test using the systest_wrapper

SCRIPT_TEST="py.test -x -s -p no:cacheprovider \
            ${PYTEST_DIR}/system/test_launchpad.py \
            ${PYTEST_DIR}/system/ns/pingpong/test_scaling.py"

test_prefix="pingpong_scaling_systest"
test_cmd=""

# Parse commonline argument and set test variables
parse_args "${@}"

# We want to run in expanded mode
collapsed_mode=false

# Construct the test command based on the test variables
construct_test_command

# Execute from pytest root directory to pick up conftest.py
cd "${PYTEST_DIR}"

eval ${test_cmd}
test_rc=$?

# display scaling log
scaling_log="${RIFT_ARTIFACTS}/scaling_${AUTO_TASK_ID}.log"
cat ${scaling_log}

exit $test_rc
