- hosts: "{{ plat }}"
  become: true
  connection: ssh
  vars_files:
    - "{{ lookup('env','PWD') }}/group_vars/os_{{ pop }}_{{ proj }}_{{ distro }}.yml"
    - "{{ lookup('env','PWD') }}/roles/{{ plat }}/vars/main.yml"

  pre_tasks:

    - local_action: shell date +'%F %T'
      register: timestamp

    - debug:
        msg: "{{ timestamp.stdout }}"

  roles:
    - nginx
