$schema: 'http://json-schema.org/draft-07/schema#'
description: A common base schema for Pishahang virtual network function descriptors
definitions:
  monitoring:
    type: object
    required:
      - name
      - unit
    additionalProperties: false
    properties:
      name:
        description: >-
          The name of the parameter to monitor. The name has to be supported by
          the service platform or the FSM.
        type: string
        pattern: '^[A-Za-z-_]+$'
      unit:
        description: The unit used to monitor (or represent) the parameter.
        oneOf:
          - const: Percentage
          - enum:
              - B
              - kB
              - KiB
              - MB
              - MiB
              - GB
              - GiB
              - TB
              - TiB
              - PT
              - PiT
          - enum:
              - bps
              - kbps
              - Mbps
              - Gbps
              - Tbps
          - enum:
              - Hz
              - kHz
              - MHz
              - GHz
              - THz
      frequency:
        description: The sample rate of the monitoring parameter.
        type: number
        exclusiveMinimum: 0
      frequency_unit:
        description: The unit of the sample frequency.
        default: Hz
        enum:
          - Hz
          - kHz
          - MHz
          - GHz
          - THz
      command:
        description: A command that is executed in order to perform custom monitoring.
        type: string
  monitoring_parameters:
    description: The various metrics and parameters to monitor.
    type: array
    items:
      description: A specific monitoring metric or parameter.
      type: object
      required:
        - name
        - unit
      additionalProperties: false
      properties:
        name:
          description: >-
            The name of the parameter to monitor. The name has to be supported
            by the service platform or the FSM.
          type: string
          pattern: '^[A-Za-z-_]+$'
        unit:
          description: The unit used to monitor (or represent) the parameter.
          oneOf:
            - const: Percentage
            - enum:
                - B
                - kB
                - KiB
                - MB
                - MiB
                - GB
                - GiB
                - TB
                - TiB
                - PT
                - PiT
            - enum:
                - bps
                - kbps
                - Mbps
                - Gbps
                - Tbps
            - enum:
                - Hz
                - kHz
                - MHz
                - GHz
                - THz
        frequency:
          description: The sample rate of the monitoring parameter.
          type: number
          exclusiveMinimum: 0
        frequency_unit:
          description: The unit of the sample frequency.
          default: Hz
          enum:
            - Hz
            - kHz
            - MHz
            - GHz
            - THz
        command:
          description: A command that is executed in order to perform custom monitoring.
          type: string
  scale_in_out:
    description: The scale-in/scale-out parameters.
    type: object
    additionalProperties: false
    properties:
      minimum:
        description: The minimum number of VDUs instantiated at any time.
        type: integer
        minimum: 1
        default: 1
      maximum:
        description: >-
          The maximum number of VDUs instantiated at any time. 0 means
          unlimited.
        type: integer
        minimum: 0
        default: 1
type: object
required:
  - descriptor_flavor
  - descriptor_type
  - descriptor_version
  - name
  - vendor
  - version
properties:
  descriptor_type:
    description: The type of the descriptor
    enum:
      - service
      - function
    const: function
  descriptor_version:
    description: The version of the descriptor definition
    type: string
    pattern: '^[A-Za-z0-9\-_.]+$'
  vendor:
    description: Unique id of the descriptor's vendor
    type: string
    pattern: '^[a-z0-9\-_.]+$'
  name:
    description: The name of the descriptor
    type: string
    pattern: '^[a-z0-9\-_.]+$'
  version:
    description: The version of the descriptor
    type: string
    pattern: '^[0-9\-_.]+$'
  author:
    description: The person or organization that created the descriptor
    type: string
  description:
    description: A description of the function or service specified by this descriptor
    type: string
  licences:
    description: Information on the descriptor's license
    type: array
    uniqueItems: true
    items:
      anyOf:
        - type: object
          required:
            - type
          additionalProperties: false
          properties:
            type:
              description: 'The type of licence, ''public'' in this case.'
              type: string
              const: public
        - type: object
          required:
            - type
            - url
          additionalProperties: false
          properties:
            type:
              description: 'The type of licence, ''private'' in this case.'
              type: string
              const: private
            url:
              description: The URL to the licence file.
              type: string
  descriptor_flavor:
    description: The flavor of the function descriptor
  monitoring_rules:
    type: array
    items:
      type: object
      required:
        - name
        - duration
        - condition
        - notification
      properties:
        name:
          description: The name of the monitoring rule
          type: string
        description:
          description: An arbitrary descritpion of this monitoring rule
          type: string
        duration:
          description: The duration the condtion has to be met before an event is fired
          type: number
        duration_unit:
          description: The unit of the durration
          ref: '#/definitions/time_units'
        condition:
          description: >-
            The condition, a boolean expression, that must be met to fire the
            event
          type: string
        notification:
          description: A list of notifications that are fired when the condition is met
          type: array
          items:
            type: object
            required:
              - name
              - type
            properties:
              name:
                description: The name of the notification
                type: string
              type:
                description: The type of message that is send to the message bus
                type: string
