@startuml

Gatekeeper -> SLM: Request service termination
SLM -> SLM: Terminate the monitoring
SLM -> Vim_Adaptor: Deconfigure WAN 
Vim_Adaptor --> SLM: Response on WAN
SLM -> Vim_Adaptor: Deconfigure SFC 
Vim_Adaptor --> SLM: Response on SFC
loop for every vnf
SLM -> OLM_or_KLM:Terminate VNF request
OLM_or_KLM --> SLM:Response on Termination call
end
SLM -> SLM: Perform Final clean up
SLM -> SMR: Terminate SSMs
SMR --> SLM: Response on termination call
SLM -> SLM: Update Records
SLM --> Gatekeeper:Update status of termination

@enduml