source 'https://rubygems.org'
ruby '2.4.3'

gem 'redis', '4.0.1'
gem 'rest-client', '2.0.2'

gem 'rake', '12.3.0'
gem 'sinatra', '2.0.0', require: 'sinatra/base'
gem 'sinatra-contrib', '2.0.0', require: false
gem 'sinatra-logger', '0.3.2'
gem 'sinatra-active-model-serializers', '0.1.0'
gem 'sinatra-cross_origin', '0.4.0'
gem 'puma', '3.11.0'
gem 'curb', '0.9.3'
gem 'rack-parser', '0.7.0', require: 'rack/parser'
gem 'ci_reporter_rspec', '1.0.0'
gem 'rubocop', '0.42.0'
gem 'rubocop-checkstyle_formatter', '0.3.0', require: false

group :test do
  gem 'rspec', '3.7.0'
  gem 'rack-test', '0.8.2'
end
