---

- debug: msg="##### SP BROKER DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

- name: run the SP Message Bus
  docker_container:
    name: "son-broker"
    image: "rabbitmq:3-management"
    env:
      RABBITMQ_CONSOLE_LOG: new
    state: started
    restart_policy: "always"
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-broker
    published_ports:
      - "5672:5672"

- wait_for: host=0.0.0.0 port=5672 timeout=30 delay=10 state=started

