#!/bin/bash

case $1 in
    start)
        /bin/bash /usr/local/bin/wim-adaptor-start.sh
    ;;
    stop)
        /bin/bash /usr/local/bin/wim-adaptor-stop.sh
    ;;
    restart)
        /bin/bash /usr/local/bin/wim-adaptor-stop.sh
        /bin/bash /usr/local/bin/wim-adaptor-start.sh
    ;;
esac
exit 0
