@startuml Microservices
top to bottom direction
skinparam componentStyle uml2

[Repository]

[Gatekeeper]

[GUI]
GUI ..> Gatekeeper

cloud {
  cloud "AWS"
  cloud "Kubernetes"
  cloud "OpenStack"
}

package "MANO Framework" {
  [Pluginmanager]
  Gatekeeper ..> Pluginmanager
  Gatekeeper ..> Repository

  package "Plugins" {
    ' VIM Adapter
    [VIM Adapter] as VIM
    Gatekeeper --> VIM
    VIM ..> AWS
    VIM ..> OpenStack
    VIM ..> Kubernetes

    [Placement]
    Placement --> VIM

    [OLM]
    OLM --> VIM

    [KLM]
    KLM --> VIM

    [ALM]
    ALM --> VIM

    ' SLM
    [SLM]
    SLM ..> Repository
    SLM --> Placement
    SLM --> OLM
    SLM --> KLM
    SLM --> ALM
    Gatekeeper --> SLM
  }

  Plugins <-> Pluginmanager
}

@enduml