#!/bin/bash

case $1 in
    start)
        /bin/bash /usr/local/bin/son-sp-infra-start.sh
    ;;
    stop)
        /bin/bash /usr/local/bin/son-sp-infra-stop.sh
    ;;
    restart)
        /bin/bash /usr/local/bin/son-sp-infra-stop.sh
        /bin/bash /usr/local/bin/son-sp-infra-start.sh
    ;;
esac
exit 0
